"""image field add in emp_m

Revision ID: 99c8b5eaca90
Revises: cc51d4eacbd9
Create Date: 2025-01-27 11:45:15.212197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c8b5eaca90'
down_revision: Union[str, None] = 'cc51d4eacbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emp_m', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emp_m', 'image')
    # ### end Alembic commands ###
