"""deleted_at field create in cs_grp_m

Revision ID: a7eab0d33057
Revises: 1e0a1da32a05
Create Date: 2024-12-29 19:05:12.790975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7eab0d33057'
down_revision: Union[str, None] = '1e0a1da32a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cs_grp_m', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cs_grp_m', 'deleted_at')
    # ### end Alembic commands ###
