"""emp_m email unique

Revision ID: cc51d4eacbd9
Revises: a10a4c670d00
Create Date: 2025-01-09 11:23:46.737224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc51d4eacbd9'
down_revision: Union[str, None] = 'a10a4c670d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_emp_m_email'), 'emp_m', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emp_m_email'), table_name='emp_m')
    # ### end Alembic commands ###
